# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-25 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20180925_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=99),
            preserve_default=False,
        ),
    ]
