# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-26 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20180926_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantiy',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
