# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20180926_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('product_price', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('pre_tax', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('total', models.IntegerField()),
                ('order_total', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('ship_to', models.CharField(max_length=255)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.User')),
            ],
        ),
    ]
