# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderLine',
        ),
    ]
