# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20180927_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='user_email',
            field=models.CharField(default=':D', max_length=255),
            preserve_default=False,
        ),
    ]
