# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_orderline_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='product_name',
            field=models.CharField(default='bob', max_length=255),
            preserve_default=False,
        ),
    ]
